# Required settings
# -----------------
token = REPLACE_WITH_TOKEN
mainServerId = 814622287366062101
inboxServerId = 814622287366062101
logChannelId = 817159479870095421

# Common settings
# ----------------------------------
prefix = =
inboxServerPermission = manageMessages
status = Highland's Community School | Support Bot!
responseMessage = Thank you for contacting us. A member of the Senior Leadership Team will be with you shortly.

# Add new options below this line:
# ----------------------------------
